name: add_site_last_page_97b5e00a-7d8e-4203-b5ec-3d3c6a11244a
label: add site configuration workflow last page output
description: quick output page that workflow is complete

type: template

extends:

labels:
  collection:
    - lib

variables:
  - name: sdwan_template
    description: template name for sd-wan hub site
    default: Hub-WEST-Template
    type_hint: hidden
  - name: sdwan_template_desc
    description: template description
    default: Hub-WEST-template
    type_hint: hidden
  - name: sdwan_stack
    description: template stack name for sd-wan site
    default: HUB-West-stack
    type_hint: hidden
  - name: sdwan_stack_desc
    description: template stack description
    default: hub site east
    type_hint: hidden
  - name: sdwan_dg
    description: device group name for sd-wan site
    default: HUB-West-device-group
    type_hint: hidden
  - name: virtual_router
    description: virtual router name to associate interfaces
    default: default
    type_hint: hidden

snippets:
  - name: workflow_output
    file: workflow_output.txt