name: get_device_list_eccc13ae-d711-4dbf-af19-0c10d26e3627

label: get list of device serial numbers

description: |
  Output Value Capturing devices for sdwan onboarding
type: rest

labels:
  collection:
    - lib

variables:
  - name: TARGET_IP
    description: Panorama IP
    default: 0.0.0.0
    type_hint: hidden
  - name: TARGET_PORT
    description: Panorama port
    default: 443
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key

# get devices
  - name: device_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/mgt-config/devices
      &key={{ api_key }}
    output_type: xml
    outputs:
      - name: device_names
        capture_pattern: ./completions/completion//@value


