# stage 1 base configuration for SD-WAN in Panorama

name: panorama_assign_device_dg_stack_eccc13ae-d711-4dbf-af19-0c10d26e3627

label: Onboard devices to Panorama
description: |
    associate individual devices to device-group and template stack

type: panorama

labels:
  collection:
    - lib

variables:
  - name: serial_number
    description: Device serial number
    default: 12345
    type_hint: dropdown
    source: device_names
  - name: sdwan_device_stack
    description: template stack name for sd-wan device
    default: SD-WAN_stack
    type_hint: dropdown
    source: stack_names
  - name: sdwan_device_dg
    description: device group for sd-wan device
    default: SD-WAN_device_group
    type_hint: dropdown
    source: device_group_names

snippets:
  - name: device_to_stack
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ sdwan_device_stack }}']/devices
    file: serial_num_entry.xml
  - name: device_to_devicegroup
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ sdwan_device_dg }}']/devices
    file: serial_num_entry.xml