# workflow demo that cleans the config, does a content update, then configures a basic internet gateway

name: sdwan_add_new_site_v90_5e0bb6b4-a407-4029-95e2-5d7389568bff
label: Step 2 - Add new SD-WAN site
description: |
  add a template, stack, and dg for a new hub or branch site. interfaces added later
  to create a topology specific template

type: workflow

labels:
    collection:
      - SD-WAN

variables:

snippets:
# workflow stages for full refresh and configuration
# add template and stack configuration
  - name: stage2_add_site_v91_97b5e00a-7d8e-4203-b5ec-3d3c6a11244b
# quick and dirty output to show completion
  - name: add_site_last_page_97b5e00a-7d8e-4203-b5ec-3d3c6a11244a