name: get_variables_lists_eccc13ae-d711-4dbf-af19-0c10d26e3627

label: Output Value Capturing variables assigned to template stack

description: |
  Output Value Capturing variables assigned to template stack
type: rest

labels:
  collection:
    - lib

variables:
  - name: TARGET_IP
    description: Panorama IP
    default: 0.0.0.0
    type_hint: hidden
  - name: TARGET_PORT
    description: Panorama port
    default: 443
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden
  - name: sdwan_device_stack
    description: template stack name for sd-wan device
    default: SD-WAN_stack
    type_hint: hidden

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key

# get stack variable names
  - name: variable_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /template-stack/entry[@name='{{ sdwan_device_stack }}']/devices/entry[@name='12345']/variable&key={{ api_key }}
    output_type: xml
    outputs:
      - name: variable_names
        capture_pattern: ./completions/completion//@value


