name: onboard_sdwan_last_page_eccc13ae-d711-4dbf-af19-0c10d26e3633
label: show interface config workflow info
description: quick output page that add intf workflow is complete

type: template

extends:

labels:
  collection:
    - lib

variables:
  - name: serial_number
    description: Device serial number
    default: 12345
    type_hint: hidden
  - name: sdwan_type
    description: template stack name for sd-wan device
    default: branch
    type_hint: hidden
snippets:
  - name: workflow_output
    file: workflow_output.txt