# stage 1 base configuration for SD-WAN in Panorama
# this is the prelude to plug-in configurations

# snippet folder name
name: stage2_add_site_v91_97b5e00a-7d8e-4203-b5ec-3d3c6a11244b
# label used for menu selection
label: SD-WAN Stage 2 add new site configuration
description: SD-WAN Stage 2 site configuration with interfaces added in later step
# type of device configuration
type: panorama

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  collection:
    - lib

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: sdwan_template
    description: template name for sd-wan site
    default: Hub-WEST-Template
    type_hint: text
  - name: sdwan_template_desc
    description: template description
    default: Hub-WEST-template
    type_hint: text
  - name: sdwan_stack
    description: template stack name for sd-wan site
    default: HUB-West-stack
    type_hint: text
  - name: sdwan_stack_desc
    description: template stack description
    default: hub site east
    type_hint: text
  - name: sdwan_dg
    description: device group name for sd-wan site
    default: HUB-West-device-group
    type_hint: text
  - name: sdwan_dg_desc
    description: device group description
    default: HUB-West-device-group
    type_hint: text
  - name: virtual_router
    description: virtual router name to associate interfaces
    default: sdwan
    type_hint: text
  - name: add_ironskillet
    description: choose to include IronSkillet day one as part of the template stack
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: template
    xpath: /config/devices/entry[@name='localhost.localdomain']/template
    file: template.xml
  - name: stack
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack
    file: stack.xml
  - name: sdwan_interface_profiles_hub
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ sdwan_template }}']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/sdwan-interface-profile
    file: sdwan_interface_profiles_hub.xml
  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ sdwan_template }}']/config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual_router.xml
  - name: sdwan_policy_prerules
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ sdwan_dg }}']/pre-rulebase/sdwan/rules
    file: sdwan_policy_prerules.xml
  - name: devicegroup_description
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ sdwan_dg }}']
    file: devicegroup_description.xml

