# stage 1 base configuration for SD-WAN in Panorama
# this skillet covers the shared device-group elements

# snippet folder name
name: sdwan_panorama_stage1_shared_dg_97b5e00a-7d8e-4203-b5ec-3d3c6a11244a
# label used for menu selection
label: SD-WAN Stage 1 configuration for device-group shared objects
description: |
  SD-WAN Stage 1 configuration for shared objects in the device-group
  including link tags, catch-all profiles, and application group
# type of device configuration
type: panorama

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  collection:
    - lib

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: sdwan_shared_template
    description: template name for sd-wan hub sites
    default: sdwan_reference_template
    type_hint: text
    help_text: this is an unused clonable template with shared attributes for reference
  - name: add_zones
    description: add zones to be used in security policy
    default: Internal
    type_hint: list

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: shared_app_group
    xpath: /config/shared/application-group
    file: shared_app_group.xml
  - name: link_tags
    xpath: /config/shared/tag
    file: link_tags.xml
  - name: shared_template
    xpath: /config/devices/entry[@name='localhost.localdomain']/template
    file: template.xml
  - name: sdwan_interface_profiles_hub
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ sdwan_shared_template }}']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/sdwan-interface-profile
    file: sdwan_interface_profiles_hub.xml
  - name: sdwan_log_forwarding_profile
    xpath: /config/shared/log-settings/profiles
    file: sdwan_log_forwarding_profile.xml
  - name: shared_profiles_catchall
    xpath: /config/shared/profiles
    file: shared_profiles_catchall.xml
  - name: traffic_distribution_profile
    xpath: /config/shared/profiles
    file: traffic_distribution_profile.xml
  - name: sdwan_catchall_postrules
    xpath: /config/shared/post-rulebase/sdwan/rules
    file: sdwan_catchall_postrules.xml
  - name: app_bgp_security_prerules
    xpath: /config/shared/pre-rulebase/security/rules
    file: app_bgp_security_prerules.xml
