name: get_interface_lists_97b5e00a-7d8e-4203-b5ec-3d3c6a11244a

label: Output Value Capturing from a PAN-OS Device for add interface menu items

description: |
  Output Value Capturing from a PAN-OS Device for add interface menu items
type: rest

labels:
  collection:
    - lib

variables:
  - name: TARGET_IP
    description: Panorama IP
    default: 0.0.0.0
    type_hint: hidden
  - name: TARGET_PORT
    description: Panorama port
    default: 443
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden
  - name: sdwan_template
    description: template name for sd-wan site
    default: Hub-WEST-Template
    type_hint: dropdown
    source: template_names

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key


# get zone names
  - name: zone_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /template/entry[@name='{{ sdwan_template }}']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone&key={{ api_key }}
    output_type: xml
    outputs:
      - name: zone_names
        capture_pattern: ./completions/completion//@value

# get virtual routers
  - name: virtual_router_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry[@name='localhost.localdomain']
      /template/entry[@name='{{ sdwan_template }}']/config/devices/entry[@name='localhost.localdomain']/network/virtual-router&key={{ api_key }}
    output_type: xml
    outputs:
      - name: virtual_router_names
        capture_pattern: ./completions/completion//@value

# get interface profiles
  - name: sdwan_intf_profile_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry[@name='localhost.localdomain']/template/
      entry[@name='{{ sdwan_template }}']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/sdwan-interface-profile&key={{ api_key }}
    output_type: xml
    outputs:
      - name: sdwan_intf_profile_names
        capture_pattern: ./completions/completion//@value


